name: geojson # you probably want to 'snapcraft register <name>'
title: 'GeoJSON'
base: core20 # the base snap is the execution environment for this snap
version: '0.24' # just for humans, typically '1.2+git' or '1.3.2'
summary: Math utility which outputs .geojson files # 79 char long summary
website: https://github.com/intheswim/geojson
description: |
  This is command line utility which performs three functions: 
  1. 'area' - outputs boundary area encircling a collection of points given the 
  minimum distance from all points in a collection. I used it to generate boundary area for a transit app for iOS store.
  2. 'eqdist' - calculates equidistant point based on three geographic coordinates.
  3. 'mincircle' - finds "min circle" (minimum bounding circle) based on a collection of input points. This function uses non-recursive randomized Welzl algorithm, applying it to spherical/geodesic case.

grade: stable # must be 'stable' to release into candidate/stable channels  (initially devel)
confinement: strict # use 'strict' once you have the right plugs and slots (also can be devmode)

donation: https://www.paypal.com/donate/?hosted_button_id=8EF7Z8LBJDT2S

parts:
  geojson:
    # See 'snapcraft plugins'
    plugin: make
    source: .
    build-packages:
      - g++
      - make

apps:
  geojson:
    command: bin/geojson
    plugs: 
    - home
